# Dados de conexão com o banco H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Configuração do cliente web do banco h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração para mostrar o SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

certidao.schedulercron=0 0 0 * * ? # Executa diariamente à meia-noite
certidao.scheduler.enabled=true

certidao.selenium.headless=false
certidao.selenium.timeout-seconds=30

certidao.empresas.cnpjs=${CERTIDAO_CNPJS}
certidao.empresas.destino=${CERTIDAO_DESTINO}

